---

install_apps: yes
configure_folders: yes

#see the homebrew role https://github.com/geerlingguy/ansible-role-homebrew
chocolatey_apps:
  - googlechrome
  - google-backup-and-sync
  - sublimetext3
  - skype
  - utorrent
  - 7zip.install
  - freecommander-xe.install
  - puntoswitcher
  - office365proplus
  - keepass.install
  - plexmediaserver
  - steam
#  - office365business
#  - teamviewer
#  - cmder
#  - jdk8
#  - intellijidea-ultimate

present_folders:
  - C:\google-drive
  - C:\movies
  - C:\games
  - C:\tv-series
  - C:\downloads