---
- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - debug: msg="ansible_facts.pkg_mgr = {{ ansible_facts.pkg_mgr }}"

    # update the default.config.yml variables with ones from config.yml if it exists
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']


  tasks:
    - include_tasks: tasks/apps.yml
      when: (install_apps and chocolatey_apps)
      tags: ['apps']

    - include_tasks: tasks/folders.yml
      when: (configure_folders and present_folders)
      tags: ['folders']